# Generated by Django 3.1.4 on 2020-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_updated_once',
            field=models.BooleanField(default=False),
        ),
    ]
